# image will be published to ghcr.io/<user>/<name>
name: hypr-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-40/solopasha-hyprland-fedora-40.repo
    install:
      - micro
      - starship
      - zlib-devel
      - libjpeg-turbo-devel
      - python3-devel
      - libpng-devel
      - libtiff-devel
      - freetype-devel
      - lcms2-devel
      - libwebp-devel
      - wireplumber-devel
      - libdbusmenu-gtk3-devel
      - playerctl-devel
      - gtk-layer-shell-devel
      - upower-devel
      - upower

      ### Basic utilities
      - axel
      - coreutils
      - cliphist
      - cmake
      - curl
      - fuzzel
      - rsync
      - ripgrep
      - gojq
      - meson
      - typescript
      - gjs

      ### Make dependencies for MicroTeX
      - tinyxml2
      - gtkmm2.4-devel
      - gtkmm3.0-devel
      - gtkmm4.0-devel
      - gtksourceviewmm
      - cairomm


      # hyprland
      #- hyprland-git
      - hyprpaper # wallpaper util
      - hyprpicker # color picker
      - hyprshot # screenshot util
      - pyprland
      - hyprcursor
      - xdg-desktop-portal-hyprland # desktop portal
      - jq
      # audio
      - pavucontrol
      - pulseaudio-utils
      - libnotify
      - pipewire
      - wireplumber
      - pamixer
      # ags
      - aylurs-gtk-shell-git
      - fzf
      - swappy
      - swww
      - fd-find
        wf-recorder

      # launcher
      - rofi-wayland

      # theme and GUI
      - adwaita-qt5
      - fontawesome-fonts-all
      - gnome-themes-extra
      - gnome-icon-theme
      - paper-icon-theme
      - breeze-icon-theme 
      - papirus-icon-theme

      - cargo
      - openssl-devel
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: script
    scripts:
      - ags-deps.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

